### ISSUE TITLE
ShareActionProvider NullPointerException

### ISSUE THREAD

**Issue by userfriendly1** [commonsguy/cw-omnibus#18]
cw-omnibus/ActionBar/ShareNative/src/com/commonsware/android/sap/MainActivity.java

on line 47 throws a null pointer exception.

**Comment by commonsguy** [comment]
@userfriendly1 It works fine for me on a Nexus 4 (Android 5.0) and an Android 4.3 emulator. If you provide me with the full stack trace, plus information about what environment you tried it on, perhaps that may give me some more clues.

**Comment by userfriendly1** [comment]
I re-imported the source code and it works now. 

I must have copied the project incorrectly the first time around.

Sorry for the inconvenience. 

Thanks for the quick response!
