### ISSUE TITLE
Mistake in Manifest for PowerHungry

### ISSUE THREAD

**Issue by RoundSparrow** [commonsguy/cw-omnibus#20]
https://github.com/commonsguy/cw-omnibus/blob/master/JobScheduler/PowerHungry/AndroidManifest.xml

The bottom of the manifest has a Receiver - should there be a dot in front of the class name?

**Comment by commonsguy** [comment]
@RoundSparrow A leading dot is not necessary. If it is not a fully-qualified class name, Android will infer that the name is relative to the `package`.
