### ISSUE TITLE
a little confusion on  EventBus/AsyncDemo

### ISSUE THREAD

**Issue by gengjiawen** [commonsguy/cw-omnibus#22]
Hi, Mark
on AsyncDemo.java there is a line 
demo.setModel(mFrag.getModel()); 
This line seems unneccessary, you can initialize model in AsyncDemoFragment.java by  using model = new ArrayList<String>() in onViewCreated().And I tested it, it works.
Is there something i am missing?

**Comment by commonsguy** [comment]
You are missing the point of the sample, which is to be able to handle configuration changes. Please read the associated book chapter. If you have further questions, please use the subscribers office hours chats.
