### ISSUE TITLE
Tutorial 11 err file not found when opening the html

### ISSUE THREAD

**Issue by jeremyp2010** [commonsguy/cw-omnibus#23]
Using Samsung Galaxy Note 4.
I first went through the tutorial and got a err_file_not_found error when trying to open the html pages in assets/misc.
When I couldn't find the difference in my code and what is in the tutorial, I copied all the code from here and the error still happens.

**Comment by commonsguy** [comment]
I just taught a course this past week, and lots of attendees worked through the tutorials and had no problems. Try your project on an emulator. If the emulator works and the Note 4 does not, then there is something goofy with the Note 4. If the project also fails on the emulator, then something is broken in your project, as I just fired up Tutorial 11 and it works fine on an emulator and on a Nexus 4.

**Comment by jeremyp2010** [comment]
Even copied all code from tut 12.  Same thing.  I will try the emulator

**Comment by jeremyp2010** [comment]
Nope.  Got the same error in the emulator
![fnf](https://cloud.githubusercontent.com/assets/10796887/5992212/13f480ac-a9e5-11e4-9588-6098bd164c3d.png)

**Comment by commonsguy** [comment]
I do not know how you are copying the code. Download the repo contents (via `git` or downloading the ZIP), then import the project you want.

**Comment by jeremyp2010** [comment]
well i got it to load the fragment but its empty.  whatever...
