### ISSUE TITLE
ActionBarSherlock

### ISSUE THREAD

**Issue by IgorGanapolsky** [commonsguy/cw-omnibus#25]
Hello, out of curiosity, why are you including ActionBarSherlock in your demos?  I mean, isn't it an old library that isn't used by companies in production anymore?

Thank you,
Igor

**Comment by commonsguy** [comment]
Most demos do not have ActionBarSherlock. The ones that do are specifically for demonstrating ActionBarSherlock, for the ActionBarSherlock chapter in my book.

**Comment by IgorGanapolsky** [comment]
I found it in the /Binding directory, which I thought should demo AIDL and Services...

**Comment by commonsguy** [comment]
Since those projects never used ActionBarSherlock, I find this difficult to believe. What file in [the `Binding/` directory](https://github.com/commonsguy/cw-omnibus/tree/master/Binding) contains a reference to ActionBarSherlock? There is no JAR file in the `libs/` directories, and a `fgrep -i` of `sher` in `*.gradle` and `*.java` turns up nothing that should be in the repo.

**Comment by IgorGanapolsky** [comment]
A simple command: `grep -r -i "actionbarsherlock" .` inside of /Binding directory produces the following:
./.idea/modules.xml:      <module fileurl="file://$PROJECT_DIR$/../external/ActionBarSherlock/ActionBarSherlock.iml" filepath="$PROJECT_DIR$/../external/ActionBarSherlock/ActionBarSherlock.iml" />
./.idea/workspace.xml:        <entry file="file://$PROJECT_DIR$/../external/ActionBarSherlock/src/com/actionbarsherlock/app/ActionBar.java">
./.idea/workspace.xml:              <option name="myItemId" value="ActionBarSherlock" />
./.idea/workspace.xml:    <entry file="file://$PROJECT_DIR$/../external/ActionBarSherlock/src/com/actionbarsherlock/app/ActionBar.java">
./.idea/workspace.xml:    <entry file="file://$PROJECT_DIR$/../external/ActionBarSherlock/src/com/actionbarsherlock/app/ActionBar.java">
./Callback/Client/project.properties:android.library.reference.1=../../external/ActionBarSherlock
./Callback/Service/project.properties:android.library.reference.1=../../external/ActionBarSherlock
./Local/Local.iml:    <orderEntry type="module" module-name="ActionBarSherlock" />
./Local/project.properties:android.library.reference.1=../../external/ActionBarSherlock
./Remote/Client/project.properties:android.library.reference.1=../../external/ActionBarSherlock
./Remote/Service/project.properties:android.library.reference.1=../../external/ActionBarSherlock

**Comment by commonsguy** [comment]
Ah, I see. I probably copied the projects from something that once had ActionBarSherlock, and since I have been focused on Android Studio, I had not noticed that Eclipse still had the dependency. There are probably other projects with similar symptoms. I'll write myself a script to clean this stuff up for Version 6.6 of the book. My apologies.

**Comment by commonsguy** [comment]
@IgorGanapolsky FYI, the head of the master branch now has these extraneous `project.properties` lines removed. Again, my apologies.

**Comment by IgorGanapolsky** [comment]
Thank you, project.properties aren't needed in Android Studio.

**Comment by commonsguy** [comment]
I know, but Eclipse/Ant need them, and the book samples still try to support those tools.

**Comment by nyxee** [comment]
Thanks a lot.
I had found the ActionbarSherlock in the mapsv2 demo too.

**Comment by nyxee** [comment]
++

how about this:

compile 'com.actionbarsherlock:actionbarsherlock:4.4.0@aar'

from

https://github.com/commonsguy/cw-omnibus/blob/master/ActionBar/ActionBarDemo/build.gradle




---------- Forwarded message ----------

**Comment by commonsguy** [comment]
@nyxee That is specifically for demonstrating ActionBarSherlock, for the ActionBarSherlock chapter in my book.

**Comment by nyxee** [comment]
thanks for the reply.
I was checking out ListNavFragmentDemoActivity under the
ActionBar\LisNavNativedemo and came across and implementation of
OnNavigationListener as deprecated....

**Comment by commonsguy** [comment]
@nyxee Correct. This is mentioned in the book.

At this point, I am going to turn off the issue tracker for this repo. The preface to the book outlines how to let me know of any bugs that you find in the book or the book's active set of sample apps.

**Comment by nyxee** [comment]
Sorry about that. Thanks for the notification..
